### ISSUE TITLE
Feedparser missing from the latest pull

### ISSUE THREAD

**Issue by matis-plx** [colloqi/pisignage-server#189]
Hi. After the latest pull node reports this error:

"internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'feedparser'
Require stack:
- C:\pisignage\pisignage-server\app\controllers\rss-feed.js
- C:\pisignage\pisignage-server\config\routes.js
- C:\pisignage\pisignage-server\config\express.js
- C:\pisignage\pisignage-server\server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\pisignage\pisignage-server\app\controllers\rss-feed.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\pisignage\pisignage-server\config\routes.js:15:15)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\pisignage\\pisignage-server\\app\\controllers\\rss-feed.js',
    'C:\\pisignage\\pisignage-server\\config\\routes.js',
    'C:\\pisignage\\pisignage-server\\config\\express.js',
    'C:\\pisignage\\pisignage-server\\server.js'
  ]
}"

If I install feedparser manually (using npm install feedparser@2.2.0), the app starts normally.

**Comment by colloqi** [comment]
After every git pull, please do npm install before restarting the server

**Comment by matis-plx** [comment]
And which version would be best to install?

**Comment by stormvansoldt** [comment]
> And which version would be best to install?

Probably the one listed in the dependencies:
`"feedparser": "^2.2.10"`
