### ISSUE TITLE
error message when starting :sudo node server.js

### ISSUE THREAD

**Issue by Pazuzo** [colloqi/pisignage-server#34]
Could you advice plese:

/home/hermes/pisignage-server/node_modules/socket.io/lib/store.js:35
Store.prototype.__proto__ = EventEmitter.prototype;
                                        ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (/home/hermes/pisignage-server/node_modules/socket.io/lib/store.js:35:41)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/hermes/pisignage-server/node_modules/socket.io/lib/manager.js:16:13)
    at Module._compile (module.js:571:32)

**Comment by colloqi** [comment]
What is the node version? we prefer node 4.x

**Comment by Pazuzo** [comment]
Thank you, thats solve the issue
